#!/bin/bash
#PBS -q workq
#PBS -l nodes=1:ppn=20
#PBS -l walltime=00:10:00
#PBS -N FBD31 
#PBS -o FBD31.out
#PBS -A loni_antfbe
#PBS -j oe 
#PBS -m abe
#PBS -M christina.kolbmann@selu.edu   


module load gcc

datapath=/work/kolbmann/FossilDates/CK-part/31
cd $datapath
mpirun -np 5 ~/rb mcmc_TEFBD.Rev 

